export const topicsData = [{ name: "Artifical Intelligence" },
{ name: "Solo maker" },
{ name: "Education" },
{ name: "Marketing" },
{ name: "Bootstrap" },
{ name: "Android" },
{ name: "Grapic Design" },
{ name: "Digital Art" },
{ name: "Github" },
{ name: "Finance" },
{ name: "Accounting" },
{ name: "Social Media" },
{ name: "Design Tools" },
{ name: "Productivity" },
{ name: "Customer Communication" },
{ name: "Developer Tools" },
{ name: "Task Management" },
{ name: "IOS" },
{ name: "Startup Lessons" },
{ name: "Online Learning" },
{ name: "Database" }] 